name       : wxmaxima
version    : 19.05.4
release    : 16
source     :
    - https://github.com/wxMaxima-developers/wxmaxima/archive/Version-19.05.4.tar.gz : e43b0a71483a78ed4d82aac5c8c7191dcc1e3a51a0d91d859446912b758de3b8
license    : GPL-2.0-or-later
component  : office.maths
summary    : Cross platform GUI for Maxima
description: |
    wxMaxima is a document based interface for the computer algebra system Maxima.
builddeps  :
    - wxwidgets-devel
rundeps    :
    - maxima
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s $installdir/usr/share/wxMaxima/testbench_simple.wxmx $installdir/usr/bin/testbench_simple.wxmx
