name       : wxmaxima
version    : 16.12.2
release    : 1
source     :
    - https://sourceforge.net/projects/wxmaxima/files/wxMaxima/16.12.2/wxmaxima-16.12.2.tar.gz : 42c0a4dfb2e2ad349a49b117ef7c2e251292fb252ce9fde16242760f3dfc4278
license    : GPL-2.0
component  : office.maths
summary    : Cross platform GUI for Maxima
description: |
    wxMaxima is a document based interface for the computer algebra system Maxima.
builddeps:
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
