name       : wxmaxima
version    : 17.10.1
release    : 3
source     :
    - https://github.com/andrejv/wxmaxima/archive/Version-17.10.1.zip : cec1e31fd7dba4051e5af18568e9ae618e300cb807c22ee721f5fa6ca11d333b
license    : GPL-2.0
component  : office.maths
summary    : Cross platform GUI for Maxima
description: |
    wxMaxima is a document based interface for the computer algebra system Maxima.
builddeps  :
    - wxwidgets-devel
rundeps    :
    - maxima
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
