name       : wxmaxima
version    : 21.02.0
release    : 18
source     :
    - https://github.com/wxMaxima-developers/wxmaxima/archive/Version-21.02.0.tar.gz : 573ab40de4e4dd3ca56d1e73fc913e3f6495c2331c4b71b1e4c48626499c0a6c
license    : GPL-2.0-or-later
component  : office.maths
summary    : Cross platform GUI for Maxima
description: |
    wxMaxima is a document based interface for the computer algebra system Maxima.
builddeps  :
    - wxwidgets-devel
rundeps    :
    - maxima
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
